#define STRING_SUBJECT 				"标题"
#define STRING_OPTIONS 				"选项"
#define STRING_COMMENT 				"正文"
#define STRING_IMAGE 				"附加图片"
#define STRING_POST_BUTTON 			"送出"
#define STRING_REPLY 				"回复"
#define STRING_NEW_THREAD 			"&#128172;&nbsp;发表新串"
#define STRING_REPLY_TO_THREAD 		"回复"
#define STRING_MY_POSTS 			"&#128100;&nbsp;我的记录"
#define STRING_UNTITLED 			"无标题"
#define STRING_UNCOMMENTED 			"无正文"
#define STRING_POSTER 				"PO"
#define STRING_ADMIN 				"管理员"
#define STRING_THREAD_SAGED 		"该串已被SAGE"
#define STRING_THREAD_LOCKED 		"该串已被锁定"
#define STRING_THREAD_DELETED 		"该串已被删除"
#define SRTING_THREAD_REPLIES_HIDE 	"回复有 %d 条被省略, 点击%s展开..."
#define SRTING_THREAD_REPLIES 		"%d 条回复"
#define STRING_NEXT_PAGE 			"下一页"
#define STRING_GALLERY_PAGE 		"相册"
#define STRING_TIMELINE_PAGE 		"时间线"
#define STRING_AUTO_RETURN 			"2s后返回<a href=\"%s\">%s</a>."
#define STRING_NEW_THREAD_SUCCESS	"成功发表新串"
#define STRING_RETURN_THREAD 		"回复成功, 2s后返回<a href=\"/thread/%d\">No.%d</a>."
#define STRING_HOMEPAGE 			"主页"
#define STRING_WEEK 				"['一', '二', '三', '四', '五', '六', '日']"
#define STRING_NO_PERMISSION		"您没有管理员权限"
#define STRING_YOUR_IP_IS_BANNED	"您的IP已被限制"
#define STRING_YOUR_ID_IS_BANNED	"您的ID已被限制"
#define STRING_COOLDOWN_TIME		"您的操作过于频繁[%s], 请稍后再试"
#define STRING_INVALID_ID			"ID错误"
#define STRING_DELETE_SUCCESS		"成功删除No.%d"
#define STRING_FILE_TOO_BIG			"文件过大, 无法上传"
#define STRING_INVALID_FILE			"不支持的文件格式, 无法上传"
#define STRING_EMPTY_COMMENT		"正文内容不能为空"
#define STRING_STOP_COOKIE			"饼干发放功能已关闭"
#define STRING_INVALID_COOKIE		"非法饼干"
#define STRING_NO_REPLY_TO_LOCKED	"不能回复已锁定的串"
#define STRING_TIMESTAMP_DISPLAY	"时间戳格式"
#define STRING_VIEW_IMAGE			"查看图片"
#define STRING_TODAY				"今天"
#define STRING_YESTERDAY			"昨天"
#define STRING_DAYS_AGO				"天前"