#include "lang.h"

char *html_form =
"<form method=\"POST\" action=\"%s\" enctype=\"multipart/form-data\">"
    "<div id='input-area' class='%s' title='%s'>"
        "<div>"
            "<table><tr>"
                "<td style='width:100%%'><input type =\"text\" name=\"input_name\" style='width:100%%' value='"STRING_UNTITLED"'/></td>"
                "<td style='text-align:right'><input class='wp-btn' type =\"submit\" value='"STRING_POST_BUTTON"'/></td>"
            "</tr></table>"
        "</div>"
        "<textarea rows='8' style='width:100%%' name = \"input_content\" id='comment'></textarea>"
        "<p>"
            "<input id='select-file' type=\"file\" name=\"input_file\" style='width:100%%;display:none'/>"
            STRING_YOU_CAN
            "<a href='javascript:void(0)' onclick='var e=document.getElementById(\"comment\");e.value += e.value ? \"\\n>>No.\" : \">>No.\";e.focus();'>"STRING_REF_A_THREAD"</a>,&nbsp;"
            "<a id='true-select' href='javascript:void(0)' onclick='document.getElementById(\"select-file\").click()'>"STRING_IMAGE"</a>,&nbsp;"
            "<select id='emoji'>"
                "<option>"STRING_INSERT_EMOJI"</option><option>&#124;&#8704;&#65439;</option><option>&#40;&#180;&#65439;&#1044;&#65439;&#96;&#41;</option><option>&#40;&#59;&#180;&#1044;&#96;&#41;</option><option>&#40;&#65344;&#65381;&#969;&#65381;&#41;</option><option>&#40;&#61;&#65439;&#969;&#65439;&#41;&#61;</option><option>&#124;&#32;&#969;&#12539;&#180;&#41;</option><option>&#124;&#45;&#96;&#32;&#41;</option><option>&#124;&#1076;&#96;&#32;&#41;</option><option>&#124;&#12540;&#96;&#32;&#41;</option><option>&#124;&#8704;&#96;&#32;&#41;</option><option>&#40;&#12388;&#1076;&#8834;&#41;</option><option>&#40;&#65439;&#1044;&#65439;&#8801;&#65439;&#1044;&#65439;&#41;</option><option>&#40;&#65342;&#111;&#65342;&#41;&#65417;</option><option>&#40;&#124;&#124;&#124;&#65439;&#1044;&#65439;&#41;</option><option>&#40;&#32;&#65439;&#8704;&#65439;&#41;</option><option>&#40;&#32;&#180;&#8704;&#96;&#41;</option><option>&#40;&#42;&#180;&#8704;&#96;&#41;</option><option>&#40;&#42;&#65439;&#8711;&#65439;&#41;</option><option>&#40;&#42;&#65439;&#12540;&#65439;&#41;</option><option>&#40;&#12288;&#65439;&#32;&#51;&#65439;&#41;</option><option>&#40;&#32;&#180;&#12540;&#96;&#41;</option><option>&#40;&#32;&#12539;&#95;&#12445;&#12539;&#41;</option><option>&#40;&#32;&#180;&#95;&#12445;&#96;&#41;</option><option>&#40;&#42;&#180;&#1076;&#96;&#41;</option><option>&#40;&#12539;&#12540;&#12539;&#41;</option><option>&#40;&#12539;&#8704;&#12539;&#41;</option><option>&#40;&#12445;&#8704;&#65381;&#41;</option><option>&#40;&#12291;&#8704;&#12291;&#41;</option><option>&#40;&#42;&#65439;&#8704;&#65439;&#42;&#41;</option><option>&#40;&#32;&#65439;&#8704;&#12290;&#41;</option><option>&#40;&#32;&#96;&#1076;&#180;&#41;</option><option>&#40;&#96;&#949;&#180;&#32;&#41;</option><option>&#40;&#96;&#12526;&#180;&#32;&#41;</option><option>&#963;&#96;&#8704;&#180;&#41;</option><option>&#32;&#65439;&#8704;&#65439;&#41;&#963;</option><option>&#65439;&#32;&#8704;&#65439;&#41;&#12494;</option><option>&#40;&#9580;&#65439;&#1076;&#65439;&#41;</option><option>&#40;&#124;&#124;&#124;&#65439;&#1076;&#65439;&#41;</option><option>&#40;&#32;&#65439;&#1076;&#65439;&#41;</option><option>&#931;&#40;&#32;&#65439;&#1076;&#65439;&#41;</option><option>&#40;&#32;&#59;&#65439;&#1076;&#65439;&#41;</option><option>&#40;&#32;&#59;&#180;&#1076;&#96;&#41;</option><option>&#40;&#12288;&#1076;&#32;&#41;&#32;&#65439;&#32;&#65439;</option><option>&#40;&#32;&#9737;&#1076;&#8857;&#41;</option><option>&#40;&#40;&#40;&#12288;&#65439;&#1076;&#65439;&#41;&#41;&#41;</option><option>&#40;&#32;&#96;&#32;&#12539;&#180;&#41;</option><option>&#40;&#32;&#180;&#1076;&#96;&#41;</option><option>&#40;&#32;&#45;&#1076;&#45;&#41;</option><option>&#40;&#62;&#1076;&#60;&#41;</option><option>&#65381;&#65439;&#40;&#32;&#65417;&#1076;&#96;&#65439;&#41;</option><option>&#40;&#32;&#84;&#1076;&#84;&#41;</option><option>&#40;&#65507;&#8711;&#65507;&#41;</option><option>&#40;&#65507;&#51;&#65507;&#41;</option><option>&#40;&#65507;&#65392;&#65507;&#41;</option><option>&#40;&#65507;&#32;&#46;&#32;&#65507;&#41;</option><option>&#40;&#65507;&#30399;&#65507;&#41;</option><option>&#40;&#65507;&#33400;&#65507;&#41;</option><option>&#40;&#65507;&#65087;&#65507;&#41;</option><option>&#40;&#65507;&#65078;&#65507;&#41;</option><option>&#12542;&#40;&#180;&#969;&#65439;&#65344;&#41;</option><option>&#40;&#42;&#180;&#969;&#96;&#42;&#41;</option><option>&#40;&#12539;&#969;&#12539;&#41;</option><option>&#40;&#32;&#180;&#12539;&#969;&#41;</option><option>&#40;&#65344;&#12539;&#969;&#41;</option><option>&#40;&#180;&#12539;&#969;&#12539;&#96;&#41;</option><option>&#40;&#96;&#12539;&#969;&#12539;&#180;&#41;</option><option>&#40;&#32;&#96;&#95;&#12387;&#180;&#41;</option><option>&#40;&#32;&#96;&#12540;&#180;&#41;</option><option>&#40;&#32;&#180;&#95;&#12387;&#96;&#41;</option><option>&#40;&#32;&#180;&#961;&#96;&#41;</option><option>&#40;&#32;&#65439;&#969;&#65439;&#41;</option><option>&#40;&#111;&#65439;&#969;&#65439;&#111;&#41;</option><option>&#40;&#12288;&#94;&#969;&#94;&#41;</option><option>&#40;&#65377;&#9685;&#8704;&#9685;&#65377;&#41;</option><option>&#47;&#40;&#32;&#9685;&#8255;&#8255;&#9685;&#32;&#41;&#92;</option><option>&#12542;&#40;&#180;&#949;&#96;&#12542;&#41;</option><option>&#40;&#12494;&#65439;&#8704;&#65439;&#41;&#12494;</option><option>&#40;&#963;&#65439;&#1076;&#65439;&#41;&#963;</option><option>&#40;&#963;&#65439;&#8704;&#65439;&#41;&#963;</option><option>&#124;&#1076;&#65439;&#32;&#41;</option><option>&#9475;&#38651;&#26609;&#9475;</option><option>&#65439;&#40;&#12388;&#1076;&#96;&#65439;&#41;</option><option>&#65439;&#8491;&#65439;&#32;&#41;&#12288;</option><option>&#8834;&#24417;&#9734;&#41;&#41;&#1076;&#96;&#41;</option><option>&#8834;&#24417;&#9734;&#41;&#41;&#1076;&#180;&#41;</option><option>&#8834;&#24417;&#9734;&#41;&#41;&#8704;&#96;&#41;</option><option>&#40;&#180;&#8704;&#40;&#40;&#9734;&#12511;&#12388;</option></select>"
            "<input type = \"text\" name = \"input_email\" class='hiding' id='opt'/>"                    
            ",&nbsp;<select id='options'>"
                "<option value=''>"STRING_OPTIONS"</option>"
                "<option value='sage'>"STRING_OPT_SAGE"</option>"
                "<option value='delete'>"STRING_OPT_DELETE"</option>"
                "<option value='url'>"STRING_OPT_URL"</option>"
            "</select>"
            "<script>"
                "document.getElementById(\"emoji\").onchange=function(e){"
                    "var em='';"
                    "var elem=document.getElementById('comment');"
                    "if(this.selectedIndex) em=this.options[this.selectedIndex].text;"
                    "this.selectedIndex=0;"
                    "if(document.selection){"
                    "    elem.focus();"
                    "    sel = document.selection.createRange();"
                    "    sel.text=em;"
                    "}"
                    "else if (elem.selectionStart||elem.selectionStart=='0') {"
                    "    var startPos=elem.selectionStart;"
                    "    var endPos=elem.selectionEnd;"
                    "    elem.value=elem.value.substring(0, startPos)+em+elem.value.substring(endPos,elem.value.length);"
                    "} else {"
                    "    elem.value+=em;"
                    "    elem.docus();"
                    "}"
                "};"
                "document.getElementById(\"options\").onchange=function(e){"
                    "document.getElementById('opt').value=this.value;"
                "};"
                "document.getElementById(\"select-file\").onchange=function(e){"
                    "var e2=document.getElementById(\"true-select\");"
                    "var filename=this.value.replace(/^.*[\\\\\\/]/, '');"
                    "e2.innerHTML='"STRING_IMAGE": '+filename;"
                "}"
            "</script>"
        "</p>"
    "</div>"
"</form>";

char *show_hide_button =
"<div id='showdiv' style='text-align: center'>"
    "<button class='wp-btn' onclick='document.getElementById(\"input-area\").className=\"\"; document.getElementById(\"showdiv\").className=\"hiding\"'>"
        "&#128172;&nbsp;"STRING_NEW_THREAD
    "</button>"
    "<button class='wp-btn' onclick='window.location=\"/list\";'>"
        "&#128100;&nbsp;"STRING_MY_POSTS
    "</button>"
"</div>";

char *html_error = 
"<script type=\"text/javascript\">"
    "setTimeout(function(){window.location=\"%s\";}, 2000);"
"</script>"
"%s, "STRING_AUTO_RETURN;

char *html_redirtothread = 
"<script type=\"text/javascript\">"
    "setTimeout(function(){window.location=\"/thread/%d\";}, 2000);"
"</script>"
STRING_RETURN_THREAD;
//char *html_emoji = 
char *html_header =
"<!DOCTYPE html>"
"<html>"
"<head>"
"<title>%s</title>"
"<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"/>"
"<meta charset='UTF-8'/><meta name='viewport' content='width=device-width,initial-scale=1,maximum-scale=1'/>"
"<style>"
".header {background:#F0E0D6; display:table; padding: 0.2em}"
".thread {margin: 3px; word-break: break-word;}"
".holder {float:left; padding: 1px; color: #ccc}"
"body{"
    "background:#ffe;"
    "font-family:'Helvetica Neue', Helvetica, Arial, sans-serif;"
    "font-size:14px;"
    "font-style:normal;"
    "font-variant:normal;"
    "font-weight:400;"
    "font-stretch:normal;"
    "line-height:20px;"
"}"
"a,a:visited{"
    "text-decoration:none;"
    "color:#21759B;"
"}"
"ttt,div[class|='div-thread'] a{"
    "color:#228811;"
"}"
"red{"
    "color:red;"
"}"
"dcyan{"
    "color:darkcyan;"
"}"
"dcyan.hand{ cursor: pointer; }"
".pager{"
    "margin:3px;"
    "padding:5px;"
    "background-color:white;"
    "border:solid 1px #ccc;"
    "line-height:2.5em;"
"}"
".pager:hover{"
    "background-color:#eee;"
"}"
".pager-inv{"
    "margin:3px;"
    "padding:5px;"
    "background-color:#39C;"
    "border:solid 1px #ccc;"
    "line-height:2.5em;"
    "color:white"
"}"
"#input-area{"
    "background-color: #fafafa;"
    "margin:0 auto;"
    "max-width:500px;"
    "-webkit-box-sizing: border-box;"
    "-moz-box-sizing: border-box;"
    "box-sizing: border-box;"
"}"
"#input-area div{"
    "border:1px solid #ccc;"
    "border-bottom: 1px dashed #ddd;"
    "border-top-right-radius: 3px;"
    "border-top-left-radius: 3px;"
    "border-bottom-right-radius: 0;"
    "border-bottom-left-radius: 0;"
    "background-color: #fafafa;"
    "display: block;"
    "width:100%%;"
    "padding:0.2em;"
    "-webkit-box-sizing: border-box;"
    "-moz-box-sizing: border-box;"
    "box-sizing: border-box;"
    "box-shadow: inset 0 1px 2px rgba(0,0,0,0.075);"
"}"
"#input-area div table tr td input[type=text]{"
    "font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;"
    "font-size:16px;"
    "padding:0.2em;"
    "border:none;"
    "background-color: #fafafa;"
"}"
"#input-area textarea{"
    "font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;"
    "font-size:16px;"
    "border:1px solid #ccc;"
    "border-top:none;"
    "border-bottom: 1px dashed #ddd;"
    "background-color: #fafafa;"
    "display: block;"
    "min-height:100px;"
    "width:100%%;"
    "padding: 0.6em;"
    "resize:vertical;"
    "-webkit-box-sizing: border-box;"
    "-moz-box-sizing: border-box;"
    "box-sizing: border-box;"
"}"
"#input-area p{"
    "background-color: #fafafa;"
    "border: 1px solid #ccc;"
    "border-top: 0;"
    "border-bottom-right-radius: 3px;"
    "border-bottom-left-radius: 3px;"
    "margin:0;"
    "padding:0.4em;"
"}"
"#input-area p select::-ms-expand {"
    "display: none;"
"}"
"select#emoji,select#options{"
    "background: transparent;"
    "border: none;"
    "-webkit-appearance: none;"
    "-moz-appearance: none;"
    "appearance: none;"
    "color: #21759B;"
    "font-size:14px;"
    "cursor:pointer;"
"}"
".postform{"
    "padding:3px;"
    "max-width:400px;"
    "width:100%%;"
    "margin:auto"
"}"
".postform tr td * {"
    "-webkit-box-sizing: border-box;"
    "-moz-box-sizing: border-box;"
    "box-sizing: border-box;"
"}"
".postform tr td:first-child{"
    // "background-color: #EA8;"
    "color: #800;"
    "font-weight: bold;"
    "padding:0.2em"
    // "min-width:80px"
"}"
".img-n{"
    "cursor:-webkit-zoom-in;"
    "max-height:250px;max-width:250px;"
    "height:expression((document.documentElement.clientHeight||document.body.clientHeight)>250?\"250px\":\"\");"
    "width:expression((document.documentElement.clientWidth||document.body.clientWidth)>250?\"250px\":\"\");"
"}"
".img-s{"
    "cursor:-webkit-zoom-in;"
    "max-height:180px;max-width:180px;"
    "height:expression((document.documentElement.clientHeight||document.body.clientHeight)>180?\"180px\":\"\");"
    "width:expression((document.documentElement.clientWidth||document.body.clientWidth)>180?\"180px\":\"\");"
"}"
".img-l{"
    "width:100%%;"
    "cursor:-webkit-zoom-out;"
"}"
".quote{"
    "margin:0.75em;"
    "font-size:120%%;"
"}"
"div.img{"
    "float:left;margin:0.5em;"
    "max-height:250px;max-width:250px;"
    "height:expression((document.documentElement.clientHeight||document.body.clientHeight)>250?\"250px\":\"\");"
    "width:expression((document.documentElement.clientWidth||document.body.clientWidth)>250?\"250px\":\"\");"
"}"
"div.file{"
    "border: dashed 1px;"
    "padding: 1em;"
"}"
"div.enlarge-s{}"
"div.enlarge-n{}"
"hr{"
    "clear:left"
"}"
"ssid{"
    "font-family: consolas"
"}"
".state{"
    "background-color:deepskyblue;"
    "color:white;"
    "padding:0.1em;"
    "border-radius:0.3em;"
    "font-size:10px;"
"}"
"#slogan{"
    "font-size:12px;"
    "margin:0.5em;"
    "padding:0.2em;"
    "line-height:1.25em;"
"}"
".hiding{"
    "display:none"
"}"
".ref{"
    "border:dashed 1px;"
    "background-color:white;"
    "font-size:80%%"
"}"
"a.button{"
    "font-size:0.7em;"
"}"
"pox{"
    "background:cadetblue;"
    "color:white;"
    "border-radius:0.4em;"
    "font-size:0.8em;"
    "padding:0em 0.4em;"
    "vertical-align:bottom;"
    "margin-left:2px;"
"}"
".wp-btn{"
    "padding:0.4em 0.6em;"
    "margin:0.2em;"
    "line-height:normal;"
    "height:auto;"
    "color:#555;"
    "border-color:#ccc;"
    "background:#f7f7f7;"
    "-webkit-box-shadow:inset 0 1px 0 #fff,0 1px 0 rgba(0,0,0,.08);"
    "vertical-align:top;"
    "display:inline-block;"
    "text-decoration:none;"
    "cursor:pointer;"
    "border-width:1px;"
    "border-style:solid;"
    "-webkit-appearance:none;"
    "-webkit-border-radius:3px;"
    "border-radius:3px;"
    "white-space:nowrap;"
    "-webkit-box-sizing:border-box;"
    "-moz-box-sizing:border-box;"
    "box-sizing:border-box;"
"}"
".wp-btn:active{"
    "background:#eee;"
    "border-color:#999;"
    "color:#333;"
    "-webkit-box-shadow:inset 0 2px 5px -3px rgba(0,0,0,.5);"
    "box-shadow:inset 0 2px 5px -3px rgba(0,0,0,.5);"
"}"
".wp-btn:hover{"
    "background:#fafafa;"
    "border-color:#999;"
    "color:#222;"
"}"
"span .wp-btn{"
    "padding:0.4em;"
    "font-size:10px;"
    "vertical-align:middle;"
"}"
"</style>"
// "<script type='text/javascript' src='http://lib.sinaapp.com/js/jquery/1.7.2/jquery.min.js'></script>"
"<script type='text/javascript'>"
"function microAjax(B,A){this.bindFunction=function(E,D){return function(){return E.apply(D,[D])}};this.stateChange=function(D){if(this.request.readyState==4){this.callbackFunction(this.request.responseText)}};this.getRequest=function(){if(window.ActiveXObject){return new ActiveXObject(\"Microsoft.XMLHTTP\")}else{if(window.XMLHttpRequest){return new XMLHttpRequest()}}return false};this.postBody=(arguments[2]||\"\");this.callbackFunction=A;this.url=B;this.request=this.getRequest();if(this.request){var C=this.request;C.onreadystatechange=this.bindFunction(this.stateChange,this);if(this.postBody!==\"\"){C.open(\"POST\",B,true);C.setRequestHeader(\"X-Requested-With\",\"XMLHttpRequest\");C.setRequestHeader(\"Content-type\",\"application/x-www-form-urlencoded\");C.setRequestHeader(\"Connection\",\"close\")}else{C.open(\"GET\",B,true)}C.send(this.postBody)}};"
"function ajst(id){"
    "if(document.getElementsByClassName){"
        "microAjax(\"/api/\"+id,function (msg){"
            "if((/(<script)/).test(msg)){window.location.href='/thread/'+id;return;}"
            "var tmp=document.getElementsByClassName('div-thread-'+id);"
            "var elems=Array.prototype.slice.call(tmp, 0);"
            "for(var i=0;i<elems.length;i++){"
                "elems[i].innerHTML=msg+'<div style=\"clear:left\"/>';"
                "elems[i].className='ref';"
            "}"
            "cvtm(false);"
        "});"
    "}"
    "else{"
        "window.location.href='/thread/'+id;"
    "}"
"};"
"function admc(id){"
    "microAjax(\"/adminconsole/\" + id, function (msg){"
        "var elem=document.getElementById('admin-'+id);"
        "elem.innerHTML=msg;"
    "});"
"};"
"function qref(id){"
    "var e=document.getElementById('comment');"
    "e.value+=e.value?('\\n>>No.'+id+'\\n'):('>>No.'+id+'\\n');"
    "e.focus();"
"};"
"function cvtm(change){"
    "if(document.getElementsByClassName){"
        "var t = 0;"
        "var ca = document.cookie.split(';');"
        "for(var i = 0; i < ca.length; ++i){"
            "if (ca[i].indexOf('timeformat') != -1)"
                "t = parseInt(ca[i].split('=')[1].trim());"
        "}"
        "if (change) t = t == 3 ? 0 : t + 1;"
        "var elems = document.getElementsByClassName('tms');"
        "var elems2 = document.getElementsByClassName('tmsc');"
        "var td = new Date();"
        "for(var i = 0; i < elems.length; i++){"
            "var d=new Date(parseInt(elems[i].innerText) * 1000);"
            "var day=d.getDate();day=day>9?day:'0'+day;"
            "var mon=d.getMonth()+1;mon=mon>9?mon:'0'+mon;"
            "var yr=d.getFullYear();"
            "var sec=d.getSeconds();sec=sec>9?sec:'0'+sec;"
            "var min=d.getMinutes();min=min>9?min:'0'+min;"
            "var hr=d.getHours();hr=hr>9?hr:'0'+hr;"
            "var wk="STRING_WEEK"[d.getDay()];"
            "elems2[i].innerHTML = '';"
            "switch(t){"
                "case 0:"
                    "elems2[i].innerHTML = yr + '/' + mon + '/' + day + '(' + wk + ')' + ' ' + hr + ':' + min + ':' + sec; break;"
                "case 1:"
                    "elems2[i].innerHTML = yr + '/' + mon + '/' + day + '(' + wk + ')'; break;"
                "case 2:"
                    "elems2[i].innerHTML = day + '/' + mon + '/' + yr + '(' + wk + ')' + ' ' + hr + ':' + min + ':' + sec; break;"
                "case 3:"
                    "function pd(d){return new Date(d.getFullYear(), d.getMonth(), d.getDate());}"
                    "var diff = (pd(td) - pd(d))/(1000*60*60*24);"
                    "diff = diff == 0 ? '"STRING_TODAY"' : (diff == 1 ? '"STRING_YESTERDAY"' : '(' + diff + ' "STRING_DAYS_AGO")');"
                    "elems2[i].innerHTML =  diff + ' ' + hr + ':' + min + ':' + sec; break;"
                "default:"
            "}"
        "}"

        "var date = new Date();"
        "date.setTime(date.getTime() + (3600 * 24 * 30 * 1000));"
        "var expires = 'expires=' + date.toGMTString();"
        "document.cookie = 'timeformat=' + t + '; ' + expires + '; path=/';"
    "}"
"};"
"function enim(id,lurl,surl){"
    "var elem=document.getElementById(id);"
    "var p=elem.parentNode;"
    "var c=elem.childNodes[0];"
    "if(c.className=='img-s'||c.className=='img-n'){"
        "p.className='enlarge-'+c.className.split('-')[1];"
        "c.className='img-l';"
        "c.src=lurl;"
        "return;"
    "}"
    "if(c.className=='img-l'){"
        "c.className='img-'+p.className.split('-')[1];"
        "p.className='img';"
        "c.src=surl;"
    "}"
"}"
"function exim(id,url){"
    "var elem=document.getElementById(id);"
    "var p=elem.parentNode;"
    "p.innerHTML='<div class=img><a href=javascript:void(0) id='+id+' onclick=enim(\"'+id+'\")><img class=img-s src=/images/'+url+'/></a></div>';"
"}"
"</script>"
"</head>"
"<body onload='cvtm(false)'>"
"<div style='text-align: center'>"
"<a href='/'><h1 style='line-height: 1.5em;'>%s</h1></a>"
"</div>";

// char * help_text =
// "cchan is an anonymous imageboard written in C/C++ \n"
// "  Option               Argument    Description  \n\n"
// "  -d, --database       PATH        set the database used by cchan \n"
// "  -r, --reset                      reset the database \n"
// "  -l, --log            LOG_PATH    set the log file name\n"
// "  -t, --title          TITLE       set site's title\n"
// "  -a, --admin-spell    PASSWORD    set admin's password \n"
// "  -T, --tpp            N           set the number of threads to show per page \n"
// "  -c, --cd-time        SECONDS     set cooldown time between two posts\n"
// "  -p, --port           PORTS       set listening port \n"
// "  -m, --salt           SALT        set md5 salt mixture \n"
// "  -A, --admin-cookie   COOKIE      set admin's cookie \n"
// "  -b, --ban-list       LIST_PATH   set the path to banlist (both IP and ID) \n"  
// "  -s, --stop-cookie                stop generating new cookies for new users \n"
// "  -i, --stop-ipcheck               stop checking IP \n"
// "  -x, --xff-ip                     use 'X-Forwarded-For' header (Apache 'ProxyPass' option) \n"
// "  -h, --help                       display this text \n";