#include "lang.h"

// The color template used by this site can be found here:
// http://www.colourlovers.com/web/trends/websites/7515/Wonderful_Copenhagen_-_k248benhavn_billige_hoteller_i_k248benhavn_ferie_k248benhavn_forlystelser_i_k248benhavn_hotel_i_k248benhavn_hotel_k248benhavn_hoteler_k248benhavn_hoteller_i_k248benhavn_hoteller_k248benhavn_kultur
// Template in short:
//  #FFFFFF
//  #E0EAF2
//  #E2DED7
//  #CECAC3
//  #F0EBE4

char *html_form =
"<form id='post-form' method=\"POST\" action=\"%s\" enctype=\"multipart/form-data\">"
    "<div id='input-area' class='%s' title='%s'>"
        "<div>"
            "<table><tr>"
                "<td style='width:100%%'><input type =\"text\" name=\"input_name\" style='width:100%%' value='"STRING_UNTITLED"'/></td>"
                "<td style='text-align:right'><input class='wp-btn' type =\"submit\" value='"STRING_POST_BUTTON"'/></td>"
            "</tr></table>"
        "</div>"
        "<textarea rows='8' style='width:100%%' name='input_content' placeholder='"STRING_CTRL_ENTER_POST"' id='comment'></textarea>"
        "<p>"
            "<input id='select-file' type=\"file\" name=\"input_file\" style='width:100%%;display:none'/>"
            STRING_YOU_CAN
            "<a href='javascript:void(0)' onclick='var e=document.getElementById(\"comment\");e.value += e.value ? \"\\n>>No.\" : \">>No.\";e.focus();'>"STRING_REF_A_THREAD"</a>,&nbsp;"
            "<a id='true-select' href='javascript:void(0)' onclick='document.getElementById(\"select-file\").click()'>"STRING_IMAGE"</a>,&nbsp;"
            "<select id='emoji'>"
                "<option>"STRING_INSERT_EMOJI"</option><option>|∀ﾟ</option><option>(´ﾟДﾟ`)</option><option>(;´Д`)</option><option>(｀･ω･)</option><option>(=ﾟωﾟ)=</option><option>| ω・´)</option><option>|-` )</option><option>|д` )</option><option>|ー` )</option><option>|∀` )</option><option>(つд⊂)</option><option>(ﾟДﾟ≡ﾟДﾟ)</option><option>(＾o＾)ﾉ</option><option>(|||ﾟДﾟ)</option><option>( ﾟ∀ﾟ)</option><option>( ´∀`)</option><option>(*´∀`)</option><option>(*ﾟ∇ﾟ)</option><option>(*ﾟーﾟ)</option><option>(　ﾟ 3ﾟ)</option><option>( ´ー`)</option><option>( ・_ゝ・)</option><option>( ´_ゝ`)</option><option>(*´д`)</option><option>(・ー・)</option><option>(・∀・)</option><option>(ゝ∀･)</option><option>(〃∀〃)</option><option>(*ﾟ∀ﾟ*)</option><option>( ﾟ∀。)</option><option>( `д´)</option><option>(`ε´ )</option><option>(`ヮ´ )</option><option>σ`∀´)</option><option> ﾟ∀ﾟ)σ</option><option>ﾟ ∀ﾟ)ノ</option><option>(╬ﾟдﾟ)</option><option>(|||ﾟдﾟ)</option><option>( ﾟдﾟ)</option><option>Σ( ﾟдﾟ)</option><option>( ;ﾟдﾟ)</option><option>( ;´д`)</option><option>(　д ) ﾟ ﾟ</option><option>( ☉д⊙)</option><option>(((　ﾟдﾟ)))</option><option>( ` ・´)</option><option>( ´д`)</option><option>( -д-)</option><option>(&gt;д&lt;)</option><option>･ﾟ( ﾉд`ﾟ)</option><option>( TдT)</option><option>(￣∇￣)</option><option>(￣3￣)</option><option>(￣ｰ￣)</option><option>(￣ . ￣)</option><option>(￣皿￣)</option><option>(￣艸￣)</option><option>(￣︿￣)</option><option>(￣︶￣)</option><option>ヾ(´ωﾟ｀)</option><option>(*´ω`*)</option><option>(・ω・)</option><option>( ´・ω)</option><option>(｀・ω)</option><option>(´・ω・`)</option><option>(`・ω・´)</option><option>( `_っ´)</option><option>( `ー´)</option><option>( ´_っ`)</option><option>( ´ρ`)</option><option>( ﾟωﾟ)</option><option>(oﾟωﾟo)</option><option>(　^ω^)</option><option>ヾ(´ε`ヾ)</option><option>(ノﾟ∀ﾟ)ノ</option><option>(σﾟдﾟ)σ</option><option>(σﾟ∀ﾟ)σ</option><option>|дﾟ )</option><option>┃電柱┃</option><option>ﾟ(つд`ﾟ)</option><option>ﾟÅﾟ )　</option><option>⊂彡☆))д`)</option><option>⊂彡☆))д´)</option><option>⊂彡☆))∀`)</option><option>(´∀((☆ミつ</option></select>"
            "<input type = \"text\" name = \"input_email\" class='hiding' id='opt'/>"                    
            ",&nbsp;<select id='options'>"
                "<option value=''>"STRING_OPTIONS"</option>"
                "<option value='sage'>"STRING_OPT_SAGE"</option>"
                "<option value='delete'>"STRING_OPT_DELETE"</option>"
                "<option value='url'>"STRING_OPT_URL"</option>"
            "</select>"
            "<script>"
                // "window.onkeyup=function(e){ ctrlDown=false; };"
                // "window.onkeydown=function(e){ if(e.keyCode==17) ctrlDown=true; };"
                "document.getElementById('comment').onkeydown=function(e){"
                    "if(e.keyCode==13&&e.ctrlKey) {"
                        "if(confirm('"STRING_CONFIRM_POST"')) document.getElementById('post-form').submit();"
                    "}"
                "};"
                "document.getElementById(\"emoji\").onchange=function(e){"
                    "var em='';"
                    "var elem=document.getElementById('comment');"
                    "if(this.selectedIndex) em=this.options[this.selectedIndex].text;"
                    "this.selectedIndex=0;"
                    "if(document.selection){"
                    "    elem.focus();"
                    "    sel = document.selection.createRange();"
                    "    sel.text=em;"
                    "}"
                    "else if (elem.selectionStart||elem.selectionStart=='0') {"
                    "    var startPos=elem.selectionStart;"
                    "    var endPos=elem.selectionEnd;"
                    "    elem.value=elem.value.substring(0, startPos)+em+elem.value.substring(endPos,elem.value.length);"
                    "} else {"
                    "    elem.value+=em;"
                    "    elem.docus();"
                    "}"
                "};"
                "document.getElementById(\"options\").onchange=function(e){"
                    "document.getElementById('opt').value=this.value;"
                "};"
                "document.getElementById(\"select-file\").onchange=function(e){"
                    "var e2=document.getElementById(\"true-select\");"
                    "var filename=this.value.replace(/^.*[\\\\\\/]/, '');"
                    "e2.innerHTML='"STRING_IMAGE"'+(filename?(': '+filename):'');"
                "}"
            "</script>"
        "</p>"
    "</div>"
"</form>";

char *show_hide_button =
"<button class='wp-btn' onclick='document.getElementById(\"input-area\").className=\"\"; document.getElementById(\"showdiv\").className=\"hiding\"'>"
    "&#128172;&nbsp;"STRING_NEW_THREAD
"</button>"
"<button class='wp-btn' onclick='window.location=\"/list\";'>"
    "&#128100;&nbsp;"STRING_MY_POSTS
"</button>";

char *html_error = 
"<script type=\"text/javascript\">"
    "setTimeout(function(){window.location=\"%s\";}, 2000);"
"</script>"
"%s, "STRING_AUTO_RETURN;

char *html_redirtothread = 
"<script type=\"text/javascript\">"
    "setTimeout(function(){window.location=\"/thread/%d\";}, 2000);"
"</script>"
STRING_RETURN_THREAD;
//char *html_emoji = 
char *html_header =
"<!DOCTYPE html>"
"<html>"
"<head>"
"<title>%s</title>"
"<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"/>"
"<meta charset='UTF-8'/><meta name='viewport' content='width=device-width,initial-scale=1,maximum-scale=1'/>"
"<link rel='icon' type='image/png' href='/images/favicon.png'>"
"<!--[if IE]><!-->"
"<link rel='stylesheet' type='text/css' href='/assets/font-ie.css'>"
"<!--<![endif]-->"
"<!--[if !IE]><!-->"
"<link rel='stylesheet' type='text/css' href='/assets/font.css'>"
"<!--<![endif]-->"
"<link rel='stylesheet' type='text/css' href='/assets/main.css'>"
// "<style>"
// ".header{"
//     "background:#E2DED7;display:table; padding: 0.5em;"
//     "border-radius:5px;"
//     "overflow: hidden;"
// "}"
// ".header:before {"
//     "content: '◆';"
//     "color:#CECAC3;"
//     "position: absolute;"
//     "margin-left: -15px;"
//     "z-index: -99;"
//     "font-size: 30px;"
// "}"
// ".wrapper .header div.reply-header{"
//     "background:#CECAC3;"
//     "margin: -0.5em;"
//     "padding: 0.5em;"
//     "border-radius:5px;"
//     "border-bottom-left-radius:0;"
//     "border-bottom-right-radius:0;"
// "}"
// ".thread {margin: 0.5em; word-break: break-word;}"
// ".holder {float:left; padding:0.6em; color: #ccc}"
// "body{"
//     "background:#F0EBE4;"
// 	"font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;"
//     "font-size:14px;"
//     "font-style:normal;"
//     "font-variant:normal;"
//     "font-weight:400;"
//     "font-stretch:normal;"
//     "line-height:20px;"
//     "margin:0;"
//     "padding:0;"
// "}"
// "a,a:visited{"
//     "text-decoration:none;"
//     "color:#21759B;"
// "}"
// "ttt,div[class|='div-thread'] a{"
//     "color:#228811;"
// "}"
// "red{"
//     "color:red;"
// "}"
// "dcyan{"
//     "color:darkcyan;"
// "}"
// "dcyan.hand{ cursor: pointer; }"
// ".pager{"
//     "margin:3px;"
//     "padding:5px;"
//     "background-color:white;"
//     "border:solid 1px #ccc;"
//     "line-height:2.5em;"
// "}"
// ".pager:hover{"
//     "background-color:#eee;"
// "}"
// ".pager-inv{"
//     "margin:3px;"
//     "padding:5px;"
//     "background-color:#39C;"
//     "border:solid 1px #ccc;"
//     "line-height:2.5em;"
//     "color:white"
// "}"
// "#input-area{"
//     // "background-color: #fafafa;"
//     "margin:0 auto;"
//     "max-width:500px;"
//     "-webkit-box-sizing: border-box;"
//     "-moz-box-sizing: border-box;"
//     "box-sizing: border-box;"
// "}"
// "#input-area div{"
//     "border:1px solid #ccc;"
//     "border-bottom: 1px dashed #ddd;"
//     "border-top-right-radius: 3px;"
//     "border-top-left-radius: 3px;"
//     "border-bottom-right-radius: 0;"
//     "border-bottom-left-radius: 0;"
//     "background-color: #fafafa;"
//     "display: block;"
//     "width:100%%;"
//     "padding:0.2em;"
//     "-webkit-box-sizing: border-box;"
//     "-moz-box-sizing: border-box;"
//     "box-sizing: border-box;"
//     "box-shadow: inset 0 1px 2px rgba(0,0,0,0.075);"
// "}"
// "#input-area div table tr td input[type=text]{"
//     "font-family: inherit;"
//     "font-size:16px;"
//     "padding:0.2em;"
//     "border:none;"
//     "background-color: #fafafa;"
// "}"
// "#input-area textarea{"
//     "font-family: inherit;"
//     "font-size:16px;"
//     "border:1px solid #ccc;"
//     "border-top:none;"
//     "border-bottom: 1px dashed #ddd;"
//     "background-color: #fafafa;"
//     "display: block;"
//     "min-height:100px;"
//     "width:100%%;"
//     "padding: 0.6em;"
//     "resize:vertical;"
//     "-webkit-box-sizing: border-box;"
//     "-moz-box-sizing: border-box;"
//     "box-sizing: border-box;"
// "}"
// "#input-area p{"
//     "background-color: #fafafa;"
//     "border: 1px solid #ccc;"
//     "border-top: 0;"
//     "border-bottom-right-radius: 3px;"
//     "border-bottom-left-radius: 3px;"
//     "margin:0;"
//     "padding:0.4em;"
// "}"
// "#input-area p select::-ms-expand {"
//     "display: none;"
// "}"
// "select#emoji,select#options{"
//     "background: transparent;"
//     "border: none;"
//     "-webkit-appearance: none;"
//     "-moz-appearance: none;"
//     "appearance: none;"
//     "color: #21759B;"
//     "font-size:14px;"
//     "cursor:pointer;"
// "}"
// "#input-area p select:hover, #input-area p a:hover {"
//     "text-decoration: underline;"
// "}"
// // ".postform{"
// //     "padding:3px;"
// //     "max-width:400px;"
// //     "width:100%%;"
// //     "margin:auto"
// // "}"
// // ".postform tr td * {"
// //     "-webkit-box-sizing: border-box;"
// //     "-moz-box-sizing: border-box;"
// //     "box-sizing: border-box;"
// // "}"
// // ".postform tr td:first-child{"
// //     // "background-color: #EA8;"
// //     "color: #800;"
// //     "font-weight: bold;"
// //     "padding:0.2em"
// //     // "min-width:80px"
// // "}"
// ".img-n{"
//     "cursor:-webkit-zoom-in;"
//     "max-height:250px;max-width:250px;"
//     "height:expression((document.documentElement.clientHeight||document.body.clientHeight)>250?\"250px\":\"\");"
//     "width:expression((document.documentElement.clientWidth||document.body.clientWidth)>250?\"250px\":\"\");"
// "}"
// ".img-s{"
//     "cursor:-webkit-zoom-in;"
//     "max-height:180px;max-width:180px;"
//     "height:expression((document.documentElement.clientHeight||document.body.clientHeight)>180?\"180px\":\"\");"
//     "width:expression((document.documentElement.clientWidth||document.body.clientWidth)>180?\"180px\":\"\");"
// "}"
// ".img-l{"
//     "width:100%%;"
//     "cursor:-webkit-zoom-out;"
// "}"
// ".quote{margin:0.75em;}"
// ".header .quote{margin-top: 1.2em;}"
// "div.img{"
//     "float:left;margin:0.5em;"
//     "max-height:250px;max-width:250px;"
//     "height:expression((document.documentElement.clientHeight||document.body.clientHeight)>250?\"250px\":\"\");"
//     "width:expression((document.documentElement.clientWidth||document.body.clientWidth)>250?\"250px\":\"\");"
// "}"
// "div.file{"
//     "border: dashed 1px;"
//     "padding: 1em;"
// "}"
// "div.enlarge-s{}"
// "div.enlarge-n{}"
// "hr{"
//     "clear:left;"
//     "border: dashed 1px #ccc;"
//     "margin: 1em;"
// "}"
// "ssid{"
//     "font-family:'PT Mono', Consolas, Arial;"
//     // "font-size: 90%%;"
//     "color: #666;"
// "}"
// // ".header .reply-header ssid{"
// //     "float:right;"
// //     "color:#888;"
// // "}"
// ".state{"
//     "background-color:deepskyblue;"
//     "color:white;"
//     "padding:0.1em;"
//     "border-radius:0.3em;"
//     "font-size:10px;"
// "}"
// "#slogan{"
//     "font-size:12px;"
//     "margin:0.5em;"
//     "padding:0.2em;"
//     "line-height:1.25em;"
// "}"
// ".hiding{"
//     "display:none"
// "}"
// ".tmsc{"
//     "color: #888;"
// "}"
// ".ref{"
//     "border:dashed 1px;"
//     "font-size:90%%"
// "}"
// "a.button{"
//     "font-size:0.7em;"
// "}"
// "pox{"
//     "background:cadetblue;"
//     "color:white;"
//     "border-radius:0.4em;"
//     "font-size:0.8em;"
//     "padding:0em 0.4em;"
//     "vertical-align:bottom;"
//     "margin-left:2px;"
// "}"
// ".wp-btn{"
//     "padding:0.4em 0.6em;"
//     "margin:0.2em;"
//     "line-height:normal;"
//     "height:auto;"
//     "color:#555;"
//     "border-color:#ccc;"
//     "background:#f7f7f7;"
//     "-webkit-box-shadow:inset 0 1px 0 #fff,0 1px 0 rgba(0,0,0,.08);"
//     "vertical-align:top;"
//     "display:inline-block;"
//     "text-decoration:none;"
//     "cursor:pointer;"
//     "border-width:1px;"
//     "border-style:solid;"
//     "-webkit-appearance:none;"
//     "-webkit-border-radius:3px;"
//     "border-radius:3px;"
//     "white-space:nowrap;"
//     "-webkit-box-sizing:border-box;"
//     "-moz-box-sizing:border-box;"
//     "box-sizing:border-box;"
// "}"
// ".wp-btn:active{"
//     "background:#eee;"
//     "border-color:#999;"
//     "color:#333;"
//     "-webkit-box-shadow:inset 0 2px 5px -3px rgba(0,0,0,.5);"
//     "box-shadow:inset 0 2px 5px -3px rgba(0,0,0,.5);"
// "}"
// ".wp-btn:hover{"
//     "background:#fafafa;"
//     "border-color:#999;"
//     "color:#222;"
// "}"
// "span .wp-btn{"
//     "padding:0.4em;"
//     "font-size:10px;"
//     "vertical-align:middle;"
// "}"
// ".page-header{"
//     "background-color: #f5f5f5;"
//     "border-bottom: solid 1px #ccc;"
//     "margin:0 auto;"
//     "max-width:800px;"
//     "box-shadow: 0 0 8px #ccc;"
// "}"
// ".page-header p{"
//     "padding: 0;"
//     "margin:0;"
// "}"
// ".page-header p a{"
//     "font-size:150%%;"
// "}"
// ".page-header p span{"
//     "cursor:pointer;"
//     "margin-right:1em;"
// "}"
// ".page-header p span:hover{"
//     "color:#4078c0;"
// "}"
// "#header-image:hover{"
//     "-webkit-filter: sepia(1);"
// "}"
// ".wrapper{"
//     "padding:0.5em;"
//     "max-width:800px;"
//     "margin:0 auto;"
// "}"
// "</style>"
// "<script type='text/javascript' src='http://lib.sinaapp.com/js/jquery/1.7.2/jquery.min.js'></script>"
"<script type='text/javascript'>"
"var ctrlDown=false;"
"function microAjax(B,A){this.bindFunction=function(E,D){return function(){return E.apply(D,[D])}};this.stateChange=function(D){if(this.request.readyState==4){this.callbackFunction(this.request.responseText)}};this.getRequest=function(){if(window.ActiveXObject){return new ActiveXObject(\"Microsoft.XMLHTTP\")}else{if(window.XMLHttpRequest){return new XMLHttpRequest()}}return false};this.postBody=(arguments[2]||\"\");this.callbackFunction=A;this.url=B;this.request=this.getRequest();if(this.request){var C=this.request;C.onreadystatechange=this.bindFunction(this.stateChange,this);if(this.postBody!==\"\"){C.open(\"POST\",B,true);C.setRequestHeader(\"X-Requested-With\",\"XMLHttpRequest\");C.setRequestHeader(\"Content-type\",\"application/x-www-form-urlencoded\");C.setRequestHeader(\"Connection\",\"close\")}else{C.open(\"GET\",B,true)}C.send(this.postBody)}};"
"function ajst(id){"
    "if(document.getElementsByClassName){"
        "microAjax(\"/api/\"+id,function (msg){"
            "if((/(<script)/).test(msg)){window.location.href='/thread/'+id;return;}"
            "var tmp=document.getElementsByClassName('div-thread-'+id);"
            "var elems=Array.prototype.slice.call(tmp, 0);"
            "for(var i=0;i<elems.length;i++){"
                "elems[i].innerHTML=msg+'<div style=\"clear:left\"/>';"
                "elems[i].className='header ref';"
            "}"
            "cvtm(false);"
        "});"
    "}"
    "else{"
        "window.location.href='/thread/'+id;"
    "}"
"};"
"function admc(id){"
    "microAjax(\"/adminconsole/\" + id, function (msg){"
        "var elem=document.getElementById('admin-'+id);"
        "elem.innerHTML=msg;"
    "});"
"};"
"function qref(id){"
    "var e=document.getElementById('comment');"
    "e.value+=e.value?('\\n>>No.'+id+'\\n'):('>>No.'+id+'\\n');"
    "e.focus();"
"};"
"function cvtm(change){"
    // "if(document.getElementsByClassName){"
    //     "var elems = document.getElementsByClassName('tms');"
    //     "var elems2 = document.getElementsByClassName('tmsc');"

    //     "var t = 0;"
    //     "var ca = document.cookie.split(';');"
    //     "for(var i = 0; i < ca.length; ++i){"
    //         "if (ca[i].indexOf('timeformat') != -1)"
    //             "t = parseInt(ca[i].split('=')[1].trim());"
    //     "}"
    //     "if (change) t = t == 3 ? 0 : t + 1;"
    //     "var td = new Date();"

    //     "function dummy(){"
    //         "var elems = document.getElementsByClassName('tms');"
    //         "var elems2 = document.getElementsByClassName('tmsc');"
    //         "for(var i = 0; i < elems.length; i++){"
    //             "var d=new Date(parseInt(elems[i].innerText) * 1000);"
    //             "var day=d.getDate();day=day>9?day:'0'+day;"
    //             "var mon=d.getMonth()+1;mon=mon>9?mon:'0'+mon;"
    //             "var yr=d.getFullYear();"
    //             "var sec=d.getSeconds();sec=sec>9?sec:'0'+sec;"
    //             "var min=d.getMinutes();min=min>9?min:'0'+min;"
    //             "var hr=d.getHours();hr=hr>9?hr:'0'+hr;"
    //             "var wk="STRING_WEEK"[d.getDay()];"
    //             "elems2[i].innerHTML = '';"
    //             "switch(t){"
    //                 "case 0:"
    //                     "elems2[i].innerHTML = yr + '/' + mon + '/' + day + '(' + wk + ')' + ' ' + hr + ':' + min + ':' + sec; break;"
    //                 "case 1:"
    //                     "elems2[i].innerHTML = yr + '/' + mon + '/' + day + '(' + wk + ')'; break;"
    //                 "case 2:"
    //                     "elems2[i].innerHTML = day + '/' + mon + '/' + yr + '(' + wk + ')' + ' ' + hr + ':' + min + ':' + sec; break;"
    //                 "case 3:"
    //                     "function pd(d){return new Date(d.getFullYear(), d.getMonth(), d.getDate());}"
    //                     "var diff = (pd(td) - pd(d))/(1000*60*60*24);"
    //                     "diff = diff == 0 ? '"STRING_TODAY"' : (diff == 1 ? '"STRING_YESTERDAY"' : '(' + diff + ' "STRING_DAYS_AGO")');"
    //                     "elems2[i].innerHTML =  diff + ' ' + hr + ':' + min + ':' + sec; break;"
    //                 "default:"
    //             "}"
    //         "}"
    //     "}"

    //     "if(elems.length<=100) dummy();"

    //     "var date = new Date();"
    //     "date.setTime(date.getTime() + (3600 * 24 * 30 * 1000));"
    //     "var expires = 'expires=' + date.toGMTString();"
    //     "document.cookie = 'timeformat=' + t + '; ' + expires + '; path=/';"
    // "}"
"};"
"function enim(id,lurl,surl){"
    "var elem=document.getElementById(id);"
    "var p=elem.parentNode;"
    "var c=elem.childNodes[0];"
    "if(c.className=='img-s'||c.className=='img-n'){"
        "p.className='enlarge-'+c.className.split('-')[1];"
        "c.className='img-l';"
        "if(lurl) c.src=lurl;"
        "return;"
    "}"
    "if(c.className=='img-l'){"
        "c.className='img-'+p.className.split('-')[1];"
        "p.className='img';"
        "if(surl) c.src=surl;"
    "}"
"}"
"function exim(id,url){"
    "var elem=document.getElementById(id);"
    "var p=elem.parentNode;"
    "p.innerHTML='<div class=img><a href=javascript:void(0) id='+id+' onclick=enim(\"'+id+'\")><img class=img-s src=/images/'+url+'/></a></div>';"
"}"
"</script>"
"</head>"
"<body>"
"<div class='page-header'>"
"<p style='float:left'><a href='/' style='vertical-align:middle'><img id='header-image' src='/images/main.png'></img></a></p>"
"<p style='float:right;margin:1em;'>"
    "<span onclick='document.getElementById(\"input-area\").className=\"\";' id='start-new-thread'>"
        "&#128172;&nbsp;"STRING_NEW_THREAD
    "</span>&nbsp;"
    "<script>"
        "if((/(thread|daerht|list)/).test(window.location.href)) document.getElementById('start-new-thread').className='hiding';"
    "</script>"
    "<span onclick='window.location.href=\"/list\";'>"
        "&#128100;&nbsp;"STRING_MY_POSTS
    "</span>"
    "<span onclick='window.location.href=\"/gallery/1\";'>"
        "&#128247;&nbsp;"STRING_GALLERY_PAGE
    "</span>"
"</p>"
"<br style='clear:both'>"
"</div>"
"<div class='wrapper'>";